package com.auto.util;

public class Constants {


    public static String OTP;
    public static int OTPSIZE = 6;
    public static String FORGOTUSERID;
    public static String UNLOCKACCOUNTURL;
    public static String TEMPORARYPASSWORD;
    public static String RESETPASSWORDLINK;
    public static boolean USER_ID_PAGE = false;
    public static boolean PASSWORD_PAGE = false;
    public static Map<String, String> responseMap;
    public static Map<String, String> requestMap = new HashMap<>();
    public static Map<String, String> englisData = new HashMap<>();
    public static Map<String, String> spanishData = new HashMap<>();
    public static Map<String, String> USERDATAFROMEXCEL = new HashMap<>();
    public static Map<String, Map<String, String>> CREDENTAILSDATA = new HashMap<String, Map<String, String>>();
    public static Map<String, String> USERCREDENTAILS = new HashMap<>();
    public static final List<String> termList = Arrays.asList("Select", "24", "30", "36", "42", "48", "54", "60", "66", "72", "78", "84");
    public static final List<String> ORIENTALNEWTERMLIST = Arrays.asList("Select", "24", "36", "48", "54", "60", "66");
    public static HashMap<String, String> PAYMENTDATA;
    public static HashMap<String, String> LOOKUPDATA;
    public static HashMap<String, String> COAPPLICANTDATA;
    public static HashMap<String, String> CREATEAPPLICATIONDATA;
    public static HashMap<String, String> EMPLOYMENTDATA;
    public static PaymentResponse PAYMENTRESPONSEPOJO = new PaymentResponse();
    public static UsernameResponse USERNAMERESPONSEPOJO = new UsernameResponse();
    public static List<PaymentSchedulesResponse> PAYMENTSCHEDULELIST = new ArrayList<>();
    public static String BALLOONPAYMENT;
    public static String APR;
    public static boolean flagBlackBook = false;
    public static boolean flagUsed = false;
    public static boolean flagVIN = false;
    public static String APPLICATIONID_REFERENCE;
    public static String GETATTRIBUTEVALUE;
    public static boolean FLAG_CO_APPLICANT = true;
    public static boolean FLAG_CO_SIGNER_1 = true;
    public static boolean FLAG_CO_SIGNER_2 = true;
    public static String MOBILEDEVICE = "desktop";
    public static boolean MOBILEEXECUTION;


    public static final String HOSTNAME = "smtp.gmail.com";
    public static final String GMAILUSERNAME = "Testofg27@gmail.com";
    public static final String GMAILPASSWORD = "sdhg zanr sllb mkvf";
    public static final String GMAILUSERNAME1 = "autoidm11@gmail.com";
    public static final String GMAILPASSWORD1 = "yosuwjhnneiyyfem";
    public static final String ENGOTPMESSAGE1 = " is your One Time Passcode requested for your Oriental Account. ";
    public static final String ENGOTPMESSAGE2 = ". DO NOT share this code with anyone. We will NEVER call or text you to request this code.";
    public static final String SPANISHOTPMESSAGE1 = "Hola, Tu código de acceso es ";
    public static final String SPANISHOTPMESSAGE2 = ". NO lo compartas. Nunca te llamaremos o enviaremos un mensaje de texto para pedirte este código.";
    public static final String ENGLISHMAILSUBJECT = "Oriental Verification";
    public static final String ENGLUserIdSUBJECT = "Username Notification";
    public static final String ESPUserIdSUBJECT = "Username Notification";
    public static final String ENGtemppwdSUBJECT = "Password Reset Notification";
    public static final String ESPtemppwdSUBJECT = "Username Notification";
    public static final String SPANISHMAILSUBJECT = "Aquí esta tu código de acceso.";
    public static final String ENGLISHINVITATIONMAILSUBJECT = "Auto Loan Application";
    public static final String SPANISHINVITATIONMAILSUBJECT = "Auto Loan Application";
    public static String INVITATION_URL;
    public static final String ENGLISH_INVITATION_LINKTEXT = "Click here to complete the Invitation process";
    public static final String TESTDATAPATH = System.getProperty("user.dir") + "/src/test/resources/testdata/";


    public static int RESENDOTPCOUNT = 0;
    public static boolean flagSkipOTP = false;
    public static String flagLanguage = "English";
    public static final String TESTEXECUTIONLANGUAGE = "English";
    public static final String HOMEPAGETITLE = "HomePage_Title";
    public static final String UserIdEmptyErrorMsg = "User_ID_Empty_Err_Message";
    public static final String UserIdPlaceholder = "User_ID_Placeholder";
    public static final String PasswordPlaceholder = "Password_placeholder";
    public static final String PasswordErrorMsg = "Password_error_Msg";
    public static final String RememberTxt = "Remember_Txt";
    public static final String LabelTroubleSignIn = "Trouble_signIn_label";
    public static final String TROUBLESIGNINLABEL = "Trouble_sign_Txt";
    public static final String ForgotUserIdTxt = "Forgot_userId_Txt";
    public static final String ForgotPasswordTxt = "Forgot_Password_Txt";
    public static final String MyAccountIsLockedTxt = "My_Account_Is_Locked_Txt";
    public static final String UserIdAddressTitle = "Address_Title_UserId";
    public static final String UserIdOrEmailAddressTitle = "Address_Title_UserId/Email";
    public static final String UserIdAddressLabel = "Address_Label_UserId";
    public static final String UserIdOrEmailAddressLabel = "Address-Label_UserId/Email";
    public static final String UserIdAddressPlaceholder = "Address_Placeholder_UserId";
    public static final String UserIdOrEmailAddressPlaceholder = "Address_Placeholder_UserId/Email";
    public static final String UserIdAddressErrorMsg = "Address_err_msg_UserId";
    public static final String UserIdOrEmailAddressErrorMsg = "Address_err_msg_UserId/Email";
    public static final String TroubleSignInVerificationTitle = "Trouble_signIn_verification_title";
    public static final String TroubleSignInVerificationSubTitle = "Trouble_signIn_verification_Subtitle";


    public static final String TroubleSignInInvalidEmailTxt = "Trouble_SignIn_Invalid_Email_Txt";
    public static final String TroubleSignInTryAgain_Txt = "Trouble_SignIn_Try_Again_Txt";
    public static final String TroubleSignInCloseTxt = "Trouble_SignIn_Close_Txt";


    public static final String OTPPageTitle = "OTP_Page_Title";
    public static final String SixDigitPinText = "Six_Digit_Pin_Txt";
    public static final String ResendCodeText = "Resend_code_Txt";
    public static final String ResendCodeLinkText = "Resend_code_link_Txt";
    public static final String WRONGUSERNAMEPASSWORD = "Enter_Wrong_Password";
    public static final String Wrong_Password_Account_Locked_Message = "Wrong_Password_Account_Locked_Message";
    public static final String SubTextInOtpPage = "SubText_OTP_Page";
    public static final String MyAccountIsLockedSubTxt = "My_Account_Is_Locked_SubTxt";
    public static final String ErrorMsgInLockedPage = "ErrorMsg_LockedPage";
    public static final String IForgotMyUserIdMessage = "IForgotMyUserId_message";
    public static final String IForgotMyPasswordMessage = "IForgotMyPassword_message";
    public static final String MyAccountIsLockedMessage = "MyAccountIsLocked_message";
    public static final String UNLOCKACCOUNTRESETMESSAGE = "MyAccountIsLocked_Reset_Message";
    public static final String valueUserId = "value_UserID";
    public static final String sendSMSTxt = "Send_SMS_Txt";
    public static final String sendVoiceCallTxt = "Send_Voice_Call_Txt";
    public static String valueHidePassword = "Value_hide_password";
    public static String valueUnHidePassword = "Value_unhide_password";
    public static String passwordMessage = "Password_Message";
    public static String changePasswordTxt = "change_password_txt";
    public static String pleaseChangePasswordTxt = "Please_Change_Password_txt";
    public static String oldPasswordTxt = "old_password_txt";
    public static String newPasswordTxt = "new_Password_txt";
    public static String confirmPasswordTxt = "Confirm_password_txt";
    public static String FORGOTUSERIDALERT = "ForgoUser_ID_Alert";
    public static String OLDPASSWORDWRONGMSG = "Old_Password_Wrong";
    public static String PASSWORDSHOULDMATCHMSG = "Password_Shouldmatch";
    public static String OTPERRORMESSAGE = "Otp_Error_Message";
    public static String PROVIDEOTPERRORMESSAGE = "Provide_OTP_Message";
    public static String OTPACCOUNTLOCKMESSAGE = "Wrong_OTP_Locked_Message";
    public static String RESENDOTP24HOURSLOCKMESSAGEUSERID = "OTP_Resend_24Hours_Lock_Message_User_ID";
    public static String RESENDOTPTEMPORARYMESSAGETSI = "OTP_Resend_Temp_Lock_Message_TSI";
    public static String RESENDOTPTEMPORARYMESSAGEUSERID = "OTP_Resend_Temp_Lock_Message_User_ID";
    public static String OTPRETRYTEMPORARYMESSAGEUSERID = "OTP_Temp_Lock_Message_User_ID";
    public static String OTPRETRY24HOURSMESSAGEUSERID = "OTP_24Hours_Lock_Message_User_ID";
    public static String RESENDOTPMESSAGE = "Resend_OTP_Message";
    public static String TSI_USER_NOTFOUND_MESSAGE = "TSI_User_NotFound_Message";
    public static String TSI_CONTACT_US_MESSAGE = "TSI_Contact_Us_Message";
    public static String TSI_ERROR_MESSAGE = "TSI_Error_Message";
    public static String TSI_UPDATING_ERROR_MESSAGE = "TSI_Updating_Error_Message";
    public static String RESETPASSWORDMESSAGE = "ResetPassword_Message";
    public static String PASSWORDCHANGEALERT = "Password_Change_Alert";
    public static String PASSWORDMUSTMESSAGE = "Password_Must_Same";
    public static String ADMINSUSPENDMESSAGE = "AdminSuspend_Message";

    //** Create Application page
    public static String LBL_DEALER_PORTAL = "Lbl_Dealer_Portal";
    public static String LBL_NOTIFICATIONS = "Lbl_Notifications";
    public static String LBL_TOTAL_APPLICATIONS = "Lbl_Total_Applications";
    public static String LBL_APPROVED = "Lbl_Approved";
    public static String LBL_DECLINED = "Lbl_Declined";
    public static String LBL_DECISION_PENDING_HEADER = "Lbl_Decision_Pending_Header";
    public static String LBL_WITHDRAWN = "Lbl_Withdrawn";
    public static String LBL_CONTRACT_VERIFICATION = "Lbl_Contract_verification";
    public static String LBL_BOOKED_APPLICATIONS = "Lbl_Booked_applications";
    public static String LBL_AMOUNT_BOOKED = "Lbl_Amount_booked";
    public static String LBL_APPLICATIONS = "Lbl_Applications";
    public static String LBL_AUTO_LOAN = "Lbl_Auto_Loan";
    public static String LBL_USER_REQUEST = "Lbl_User_Request";
    public static String LBL_CREATE_APPLICATION = "Lbl_Create_Application";
    public static String MANDATORYFIELD_ERROR_MESSAGE = "Error_Mandatory_Field";
    public static String MAXIMUM25CHARACTERS_ERROR_MESSAGE = "Error_Max_25_Chars";
    public static String INVALIDFORMAT_ERROR_MESSAGE = "Error_Invalid_Format";
    public static String DATE_FORMAT_ERROR_MESSAGE = "Error_Date_Format";
    public static String MINOR_DOB_ERROR_MESSAGE = "Error_Minor_DOB";
    public static String MORETHAN_150_YEARS_ERROR_MESSAGE = "Error_Morethan_150_Years";
    public static String SSN_LENGTH_ERROR_MESSAGE = "Error_SSN_Length";
    public static String LASTNAME_ERROR_MESSAGE = "Error_LastName";
    public static String LASTNAME_ALPHA_ERROR_MESSAGE = "Error_LastName_Alpha";
    public static String INVALID_EMAIL_FORMAT_ERROR_MESSAGE = "Error_Invalid_Email_Format";
    public static String MOBILE_NUMBER_ERROR_MESSAGE = "Error_Mobile_Number";
    public static String ALTERNATE_PHONE_NUMBER_ERROR_MESSAGE = "Error_Alternate_Phone_Number";
    public static String WORK_PHONE_NUMBER_ERROR_MESSAGE = "Error_Work_Phone_Number";
    public static String ENTER_VALID_VALUE_MESSAGE = "Error_Enter_Valid_Value";
    public static String ZIPCODE_LENTH_ERROR_MESSAGE = "Error_ZipCode_Length";
    public static String ZIPCODE_LENTH_ERROR_MESSAGE1 = "Error_ZipCode_Length1";
    public static String PLEASE_UPLOAD_ADDRESS_PROOF = "Lbl_Please_Upload_Address_Proof";
    public static String INVALID_MONTH_ERROR_MESSAGE = "Error_Invalid_Month";
    public static String GREATERTHAN_AGE_ERROR_MESSAGE = "Error_Greaterthan_Age";
    public static String LBL_UTILITYBILL = "Lbl_UtilityBill";
    public static String LBL_VERIFY_YOUR_IDENTITY = "Lbl_Verify_Your_Identity";
    public static String LBL_UPLOADAD_PROOF_OF_ADDRESS = "Lbl_Upload_proof_of_Address";
    public static String LBL_BASIC_INFORMATION = "Lbl_Basic_Information";
    public static String LBL_DEMOGRAPHIC_INFORMATION = "Lbl_Demographic_Information";
    public static String LBL_RESIDENTIAL_ADDRESS = "Lbl_Residential_Address";
    public static String LBL_MAILING_ADDRESS = "Lbl_Mailing_Address";
    public static String LBL_RESIDENTIAL_STATUS = "Lbl_Residential_Status";
    public static String LBL_RESIDENT_STATUS = "Lbl_Resident_Status";
    public static String LBL_EMPLOYMENT_INFORMATION = "Lbl_Employment_Information";
    public static String LBL_ADDITIONAL_INCOME = "Lbl_Additional_Income";
    public static String LBL_DI_APPLICANT = "Lbl_Demographic_Information_Applicant";
    public static String LBL_DI_CO_APPLICANT = "Lbl_Demographic_Information_Co_Applicant";
    public static String LBL_DI_CO_SIGNER1 = "Lbl_Demographic_Information_Co_Signer1";
    public static String LBL_DI_CO_SIGNER2 = "Lbl_Demographic_Information_Co_Signer2";
    public static String LBL_EMP_PRIMARY_APPLICANT = "Lbl_Employment_Information_Applicant";
    public static String LBL_EMP_CO_APPLICANT = "Lbl_Employment_Information_Co_Applicant";
    public static String LBL_EMP_CO_SIGNER1 = "Lbl_Employment_Information_Co_Signer1";
    public static String LBL_EMP_CO_SIGNER2 = "Lbl_Employment_Information_Co_Signer2";
    public static String LBL_COLLATERAL_INFOMRATION = "Lbl_Collateral_Information";
    public static String LBL_FINANCING_TERMS = "Lbl_Financing_Terms";
    public static String LBL_FINANCIAL_TERMS = "Lbl_Financial_Terms";
    public static String LBL_ESTIMATED_MONTHLY_PAYMENT = "Lbl_Estimated_Monthly_Payment";
    public static String LBL_PAYMENT_SCHEDULE = "Lbl_Payment_Schedule";
    public static String LBL_PAYMENT_CALCULATOR_DETAILS = "Lbl_Payment_Calculator_Details";
    public static String LBL_ITEMIZED_AMOUNT_FINANED = "Lbl_Itemization_Of_Amount_Financed";
    public static String LBL_INSURANCE = "Lbl_Insurance";
    public static String LBL_FEES = "Lbl_Fees";
    public static String LBL_DEFERRED_PAYMENT = "Lbl_Deferred_Payment";
    public static String LBL_VEHICLE_VALUES = "Lbl_Vehicle_Values";
    public static String LBL_APPLICATION_SUBMITTED = "Lbl_Application_Submitted";
    public static String LBL_APPLICATION_UNDER_REVIEW = "Lbl_Application_Under_Review";
    public static String LBL_DECISION_PENDING = "Lbl_Decision_Pending";
    public static String LBL_Declined = "Lbl_Declined";
    public static String LBL_INVITATION_EMAIL_MANDATORY = "Lbl_Invitation_eMail_Mandatory";
    public static String LBL_INVITATION_SENT_SUCCESSFUL = "Lbl_Invitation_Sent";
    public static String LBL_AUTO_LOAN_INVITATION_HEADING = "Lbl_Auto_Loan_Invitation_Heading";
    public static String LBL_NO_RECORDS_FOUND = "No record/s found";
    public static String LBL_YOUR_CONCERT = "Lbl_Your_Consent";
    public static final String LINK_ESIGN_DISCLOSURE = "https://oriental-common-consentform-ref-data-qa.s3.amazonaws.com/auto/linkedConsents/en_E-Sign_Disclosure.pdf?";
    public static final String LINK_PRIVACY_POLICY = "https://oriental-common-consentform-ref-data-qa.s3.amazonaws.com/auto/linkedConsents/en_Privacy_Policy.pdf?";
    public static final String LBL_INVITATION_COMPLETED = "Lbl_Invitation_Completed";
    public static final String LBL_INVITATION_SUBMITTED = "Lbl_Invitation_Submitted";
    public static final String LBL_INVITATION_ALREDY_SUBMITTED = "Lbl_Invitation_Already_Submitted";
    public static final String LBL_NOT_VERIFIED = "Lbl_Not_Verified";
    public static String APPLICATIONID;
    public static String APPLICATION_STATUS;

    public static final String PRIMARYAPPLICANT = "Primary Applicant";
    public static JSONObject DEVTOOLSRESPONSEJSON = null;


}
